In [1]:
import pandas as pd 
import numpy as np
from warnings import filterwarnings
filterwarnings("ignore")

In [2]:
df = pd.read_csv("C:/Users/Mohammad asif/Downloads/archive (9)/fake_job_postings.csv")

In [3]:
df.tail(5)

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
17875,17876,Account Director - Distribution,"CA, ON, Toronto",Sales,NaN,Vend is looking for some awesome new talent to...,Just in case this is the first time you’ve vis...,To ace this role you:Will eat comprehensive St...,What can you expect from us?We have an open cu...,0,1,1,Full-time,Mid-Senior level,NaN,Computer Software,Sales,0
17876,17877,Payroll Accountant,"US, PA, Philadelphia",Accounting,NaN,WebLinc is the e-commerce platform and service...,The Payroll Accountant will focus primarily on...,- B.A. or B.S. in Accounting- Desire to have f...,Health &amp; WellnessMedical planPrescription ...,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Internet,Accounting/Auditing,0
17877,17878,Project Cost Control Staff Engineer - Cost Con...,"US, TX, Houston",NaN,NaN,We Provide Full Time Permanent Positions for m...,Experienced Project Cost Control Staff Enginee...,At least 12 years professional experience.Abil...,NaN,0,0,0,Full-time,NaN,NaN,NaN,NaN,0
17878,17879,Graphic Designer,"NG, LA, Lagos",NaN,NaN,NaN,Nemsia Studios is looking for an experienced v...,1. Must be fluent in the latest versions of Co...,Competitive salary (compensation will be based...,0,0,1,Contract,Not Applicable,Professional,Graphic Design,Design,0
17879,17880,Web Application Developers,"NZ, N, Wellington",Engineering,NaN,Vend is looking for some awesome new talent to...,Who are we?Vend is an award winning web based ...,We want to hear from you if:You have an in-dep...,NaN,0,1,1,Full-time,Mid-Senior level,NaN,Computer Software,Engineering,0

In [4]:
df.describe()

,job_id,telecommuting,has_company_logo,has_questions,fraudulent
count,17880.000000,17880.000000,17880.000000,17880.000000,17880.000000
mean,8940.500000,0.042897,0.795302,0.491723,0.048434
std,5161.655742,0.202631,0.403492,0.499945,0.214688
min,1.000000,0.000000,0.000000,0.000000,0.000000
25%,4470.750000,0.000000,1.000000,0.000000,0.000000
50%,8940.500000,0.000000,1.000000,0.000000,0.000000
75%,13410.250000,0.000000,1.000000,1.000000,0.000000
max,17880.000000,1.000000,1.000000,1.000000,1.000000

In [5]:
df['fraudulent'].value_counts()

fraudulent
0    17014
1      866
Name: count, dtype: int64

In [6]:
df.isnull().sum()

job_id                     0
title                      0
location                 346
department             11547
salary_range           15012
company_profile         3308
description                1
requirements            2696
benefits                7212
telecommuting              0
has_company_logo           0
has_questions              0
employment_type         3471
required_experience     7050
required_education      8105
industry                4903
function                6455
fraudulent                 0
dtype: int64

In [7]:
df.describe()

,job_id,telecommuting,has_company_logo,has_questions,fraudulent
count,17880.000000,17880.000000,17880.000000,17880.000000,17880.000000
mean,8940.500000,0.042897,0.795302,0.491723,0.048434
std,5161.655742,0.202631,0.403492,0.499945,0.214688
min,1.000000,0.000000,0.000000,0.000000,0.000000
25%,4470.750000,0.000000,1.000000,0.000000,0.000000
50%,8940.500000,0.000000,1.000000,0.000000,0.000000
75%,13410.250000,0.000000,1.000000,1.000000,0.000000
max,17880.000000,1.000000,1.000000,1.000000,1.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17880 entries, 0 to 17879
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   job_id               17880 non-null  int64
 1   title                17880 non-null  object
 2   location             17534 non-null  object
 3   department           6333 non-null   object
 4   salary_range         2868 non-null   object
 5   company_profile      14572 non-null  object
 6   description          17879 non-null  object
 7   requirements         15184 non-null  object
 8   benefits             10668 non-null  object
 9   telecommuting        17880 non-null  int64
 10  has_company_logo     17880 non-null  int64
 11  has_questions        17880 non-null  int64
 12  employment_type      14409 non-null  object
 13  required_experience  10830 non-null  object
 14  required_education   9775 non-null   object
 15  industry             12977 non-null  object
 16  function             11425 non-null  object
 17  fraudulent           17880 non-null  int64
dtypes: int64(5), object(13)
memory usage: 2.5+ MB

In [9]:
df.shape

(17880, 18)

In [10]:
df.columns

Index(['job_id', 'title', 'location', 'department', 'salary_range',
       'company_profile', 'description', 'requirements', 'benefits',
       'telecommuting', 'has_company_logo', 'has_questions', 'employment_type',
       'required_experience', 'required_education', 'industry', 'function',
       'fraudulent'],
      dtype='object')

In [11]:
df['department'].fillna("unknown", inplace=True)

In [12]:
df['employment_type'].fillna("unknown", inplace=True)

In [13]:
df['required_experience'].fillna("unknown", inplace=True)

In [14]:
df['required_education'].fillna("unknown", inplace=True)

In [15]:
df['industry'].fillna("unknown", inplace=True)

In [16]:
df["function"].fillna("unknown", inplace=True)

In [17]:
df["company_profile"].fillna("unknown", inplace=True)

In [18]:
df["company_profile"].fillna("No information", inplace=True)

In [19]:
df['description'].fillna("No description", inplace=True)

In [20]:
df['requirements'].fillna("Not specified", inplace=True)

In [21]:
df['benefits'].fillna("Not mentioned", inplace=True)

In [22]:
# Splitting salary range and filling missing values
df[['min_salary', 'max_salary']] = df['salary_range'].str.split('-', expand=True)

In [23]:
df['min_salary'] = pd.to_numeric(df['min_salary'], errors='coerce').fillna("unknown")

In [24]:
df["max_salary"] = pd.to_numeric(df['max_salary'], errors = 'coerce').fillna("unknown")

In [25]:
location_split = df['location'].str.split(',', expand=True)

In [26]:
# Assign values ensuring correct order (Country, State, City)
df['country'] = location_split[0].fillna("Unknown")

In [27]:
df['state'] = location_split[1].fillna("Unknown")

In [28]:
df['city'] = location_split[2].fillna("Unknown")

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17880 entries, 0 to 17879
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   job_id               17880 non-null  int64
 1   title                17880 non-null  object
 2   location             17534 non-null  object
 3   department           17880 non-null  object
 4   salary_range         2868 non-null   object
 5   company_profile      17880 non-null  object
 6   description          17880 non-null  object
 7   requirements         17880 non-null  object
 8   benefits             17880 non-null  object
 9   telecommuting        17880 non-null  int64
 10  has_company_logo     17880 non-null  int64
 11  has_questions        17880 non-null  int64
 12  employment_type      17880 non-null  object
 13  required_experience  17880 non-null  object
 14  required_education   17880 non-null  object
 15  industry             17880 non-null  object
 16  function             17880 non-null  object
 17  fraudulent           17880 non-null  int64
 18  min_salary           17880 non-null  object
 19  max_salary           17880 non-null  object
 20  country              17880 non-null  object
 21  state                17880 non-null  object
 22  city                 17880 non-null  object
dtypes: int64(5), object(18)
memory usage: 3.1+ MB

In [30]:
df.drop(columns=['location','salary_range'], inplace = True)

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17880 entries, 0 to 17879
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   job_id               17880 non-null  int64
 1   title                17880 non-null  object
 2   department           17880 non-null  object
 3   company_profile      17880 non-null  object
 4   description          17880 non-null  object
 5   requirements         17880 non-null  object
 6   benefits             17880 non-null  object
 7   telecommuting        17880 non-null  int64
 8   has_company_logo     17880 non-null  int64
 9   has_questions        17880 non-null  int64
 10  employment_type      17880 non-null  object
 11  required_experience  17880 non-null  object
 12  required_education   17880 non-null  object
 13  industry             17880 non-null  object
 14  function             17880 non-null  object
 15  fraudulent           17880 non-null  int64
 16  min_salary           17880 non-null  object
 17  max_salary           17880 non-null  object
 18  country              17880 non-null  object
 19  state                17880 non-null  object
 20  city                 17880 non-null  object
dtypes: int64(5), object(16)
memory usage: 2.9+ MB

In [32]:
df.isnull().sum()

job_id                 0
title                  0
department             0
company_profile        0
description            0
requirements           0
benefits               0
telecommuting          0
has_company_logo       0
has_questions          0
employment_type        0
required_experience    0
required_education     0
industry               0
function               0
fraudulent             0
min_salary             0
max_salary             0
country                0
state                  0
city                   0
dtype: int64

In [33]:
df.head(50)

,job_id,title,department,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,...,required_experience,required_education,industry,function,fraudulent,min_salary,max_salary,country,state,city
0,1,Marketing Intern,Marketing,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,Not mentioned,0,1,0,...,Internship,unknown,unknown,Marketing,0,unknown,unknown,US,NY,New York
1,2,Customer Service - Cloud Video Production,Success,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,...,Not Applicable,unknown,Marketing and Advertising,Customer Service,0,unknown,unknown,NZ,,Auckland
2,3,Commissioning Machinery Assistant (CMA),unknown,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,Not mentioned,0,1,0,...,unknown,unknown,unknown,unknown,0,unknown,unknown,US,IA,Wever
3,4,Account Executive - Washington DC,Sales,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,...,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0,unknown,unknown,US,DC,Washington
4,5,Bill Review Manager,unknown,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,...,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0,unknown,unknown,US,FL,Fort Worth
5,6,Accounting Clerk,unknown,unknown,Job OverviewApex is an environmental consultin...,Not specified,Not mentioned,0,0,0,...,unknown,unknown,unknown,unknown,0,unknown,unknown,US,MD,
6,7,Head of Content (m/f),ANDROIDPIT,"Founded in 2009, the Fonpit AG rose with its i...",Your Responsibilities: Manage the English-spea...,Your Know-How: ...,Your Benefits: Being part of a fast-growing co...,0,1,1,...,Mid-Senior level,Master's Degree,Online Media,Management,0,20000.0,28000.0,DE,BE,Berlin
7,8,Lead Guest Service Specialist,unknown,Airenvy’s mission is to provide lucrative yet ...,Who is Airenvy?Hey there! We are seasoned entr...,"Experience with CRM software, live chat, and p...",Competitive Pay. You'll be able to eat steak e...,0,1,1,...,unknown,unknown,unknown,unknown,0,unknown,unknown,US,CA,San Francisco
8,9,HP BSM SME,unknown,Solutions3 is a woman-owned small business who...,Implementation/Configuration/Testing/Training ...,MUST BE A US CITIZEN.An active TS/SCI clearanc...,Not mentioned,0,1,1,...,Associate,unknown,Information Technology and Services,unknown,0,unknown,unknown,US,FL,Pensacola
9,10,Customer Service Associate - Part Time,unknown,"Novitex Enterprise Solutions, formerly Pitney ...",The Customer Service Associate will be based i...,Minimum Requirements:Minimum of 6 months custo...,Not mentioned,0,1,0,...,Entry level,High School or equivalent,Financial Services,Customer Service,0,unknown,unknown,US,AZ,Phoenix
10,11,ASP.net Developer Job opportunity at United St...,unknown,unknown,Position : #URL_86fd830a95a64e2b30ceed829e63fd...,Position : #URL_86fd830a95a64e2b30ceed829e63fd...,Benefits - FullBonus Eligible - YesInterview T...,0,0,0,...,Mid-Senior level,Bachelor's Degree,Information Technology and Services,Information Technology,0,100000.0,120000.0,US,NJ,Jersey City
11,12,Talent Sourcer (6 months fixed-term contract),HR,Want to build a 21st century financial service...,TransferWise is the clever new way to move mon...,We’re looking for someone who:Proven track rec...,You will join one of Europe’s most hotly tippe...,0,1,0,...,unknown,unknown,unknown,unknown,0,unknown,unknown,GB,LND,London
12,13,"Applications Developer, Digital",unknown,"Novitex Enterprise Solutions, formerly Pitney ...","The Applications Developer, Digital will devel...",Requirements:4 – 5 years’ experience in develo...,Not mentioned,0,1,0,...,Associate,Bachelor's Degree,Management Consulting,Information Technology,0,unknown,unknown,US,CT,Stamford
13,14,Installers,unknown,Growing event production company providing sta...,"Event Industry Installers Needed!! (Orlando, F...","Valid driver's license,Somewhat Clean driving ...",Not mentioned,0,1,1,...,Not Applicable,Unspecified,Events Services,Other,0,unknown,unknown,US,FL,Orlando
14,15,Account Executive - Sydney,Sales,Adthena is the UK’s leading competitive intell...,Are you interested in a satisfying and financi...,You’ll need to be smart and passionate and hav...,"In return we'll pay you well, give you some ow...",0,1,0,...,Associate,Bachelor's Degree,Internet,Sales,0,unknown,unknown,AU,NSW,Sydney
15,16,VP of Sales - Vault Dragon,Sales,Jungle Ventures is the leading Singapore based...,About Vault Dragon Vault Dragon is Dropbox for...,Key Superpowers3-5 years of high-pressure sale...,"Basic: SGD 120,000Equity negotiable for a rock...",0,1,1,...,Executive,Bachelor's Degree,Facilities Services,Sales,0,120000.0,150000.0,SG,01,Singapore
16,17,Hands-On QA Leader,R&D,At HoneyBook we’re re-imagining the events ind...,We are looking for a Hands-On QA Leader for ou...,Previous experience in client &amp; server tes...,Not mentioned,0,1,0,...,Mid-Senior level,unknown,Internet,Engineering,0,unknown,unknown,IL,,Tel Aviv
17,18,Southend-on-Sea Traineeships Under NAS 16-18 Y...,unknown,Established on the principles that full time e...,Government funding is only available for 16-18...,16-18 year olds only due to government funding...,Career prospects.,0,1,1,...,unknown,unknown,unknown,unknown,0,unknown,unknown,GB,SOS,Southend-on-Sea
18,19,Visual Designer,unknown,Kettle is an independent digital agency based ...,Kettle is hiring a Visual Designer!Job Locatio...,Not specified,Not mentioned,0,1,0,...,unknown,unknown,unknown,unknown,0,unknown,unknown,US,NY,New York
19,20,Process Controls Engineer - DCS PLC MS Office ...,unknown,We Provide Full Time Permanent Positions for m...,Experienced Process Controls Engineer is requi...,Must have 5 or more years of experience with D...,Not mentioned,0,0,0,...,unknown,unknown,unknown,unknown,0,unknown,unknown,US,PA,USA Northeast
20,21,Marketing Assistant,unknown,IntelliBright was created to leverage enterpri...,IntelliBright is growing fast and is looking f...,Job RequirementsAssist in creating client onli...,Not mentioned,0,1,0,...,unknown,unknown,unknown,Marketing,0,unknown,unknown,US,TX,Austin
21,22,Front End Developer,unknown,Frustrated with the status quo?Like to re-imag...,Want to be part of a globally focused tech tea...,You will most likely have:A solid mastery of m...,You will be part of an awesome team of innovat...,0,1,0,...,Mid-Senior level,Master's Degree,Consumer Electronics,Engineering,0,unknown,unknown,NZ,N,Auckland
22,23,Engagement Manager,Engagement,Upstream’s mission is to revolutionise the way...,The position reports to the Head of Engagement...,RequirementsThe ideal candidate will be bright...,Salary &amp; BenefitsThe opportunity to learn ...,0,1,1,...,Mid-Senior level,Bachelor's Degree,Telecommunications,Sales,0,unknown,unknown,AE,,
23,24,"Vice President, Sales and Sponsorship (Busines...",Businessfriend.com,"WDM Group is an innovative, forward thinking d...",#URL_eda2500ddcedb60957fcd7f5b164e092966f8c4e8...,"Job Requirements:A reputation as a ""go-getter""...",Businessfriend will offer a competitive six fi...,0,1,0,...,Executive,Unspecified,Internet,Sales,0,100000.0,120000.0,US,CA,Carlsbad
24,25,Customer Service,unknown,unknown,We are a canary wharf based e-commerce company...,Not specified,Not mentioned,0,0,0,...,unknown,unknown,unknown,unknown,0,unknown,unknown,GB,LND,London
25,26,H1B SPONSOR FOR L1/L2/OPT,unknown,i28 Technologies has demonstrated expertise in...,"Hello,Wish you are doing good... ...","JAVA, .NET, SQL, ORACLE, SAP, Informatica, Big...",Not mentioned,0,1,1,...,unknown,unknown,unknown,unknown,0,unknown,unknown,US,NY,New York
26,27,Marketing Exec,Marketing,If working in a cubical seems like your idea o...,We are currently expanding our Marketing Depar...,"This position is Junior to Mid level. Ideally,...",We are looking for Singaporean residents or in...,0,1,0,...,Associate,unknown,Online Media,Marketing,0,unknown,unknown,SG,,
27,28,HAAD/DHA Licensed Doctors Opening in UAE,Medical,We the Medical Recruitment Team of Roland and ...,HAAD/DHA Licensed Doctors Opening in UAEWe the...,RequirementsEndocrinologistGastroenterologistC...,Our client is one of the reputed and leading H...,0,1,0,...,Associate,Master's Degree,Hospital & Health Care,Health Care Provider,0,unknown,unknown,AE,AZ,Abudhabi
28,29,Talent Management Process Manager,unknown,We Provide Full Time Permanent Positions for m...,(We have more than 1500+ Job openings in our w...,Not specified,Not mentioned,0,0,0,...,unknown,unknown,Management Consulting,unknown,0,unknown,unknown,US,MO,St. Louis
29,30,Customer Service Associate,unknown,"Novitex Enterprise Solutions, formerly Pitney ...",The Customer Service Associate will be based i...,Minimum Requirements:Minimum of 1 year custome...,Not mentioned,0,1,0,...,Entry level,High School or equivalent,Consumer Services,Administrative,0,unknown,unknown,CA,ON,Toronto
30,31,Customer Service Technical Specialist,unknown,"Novitex Enterprise Solutions, formerly Pitney ...",The Customer Service Technical Specialist will...,Qualifications:Minimum of 6 months customer se...,Not mentioned,0,1,0,...,Entry level,High School or equivalent,Computer Software,Customer Service,0,unknown,unknown,US,MA,Waltham
31,32,Software Applications Specialist,unknown,unknown,"Day to Day-Install, upgrade and configure web-...",Must Have's3+ years of experience with web-bas...,"Medical, Dental, Vision, Life, Disability, Pre...",0,1,0,...,Associate,Unspecified,Computer Software,Engineering,0,50000.0,65000.0,US,KS,
32,33,Craftsman Associate,Field,"We are an award-winning team of professionals,...",Construction: Entry-Level Craftsman Associate ...,Requirements: (Please do not apply if you do ...,Benefits: Hourly plus commissions. Work with ...,0,1,1,...,Entry level,Unspecified,Construction,Other,0,unknown,unknown,US,WA,Everett
33,34,Completion Engineer,unknown,Valor Services provides Workforce Solutions th...,About the CompanyThis is an amazing job opport...,Education:Bachelor of Science in Petroleum Eng...,Not mentioned,0,1,1,...,unknown,Bachelor's Degree,Oil & Energy,Engineering,0,unknown,unknown,US,CA,San Ramon
34,35,I Want To Work At Karmarama,All,At Karmarama we have a unique hiring policy: n...,Didn't see a role for you? Don't fret. We’re a...,Hey!Thanks again for applying to Karmarama and...,Not mentioned,0,1,1,...,unknown,unknown,Marketing and Advertising,unknown,0,unknown,unknown,GB,LND,
35,36,English Teacher Abroad,unknown,We help teachers get safe &amp; secure jobs ab...,"Play with kids, get paid for it Love travel? J...",University degree required. TEFL / TESOL / CEL...,See job description,0,1,1,...,unknown,Bachelor's Degree,Education Management,unknown,0,unknown,unknown,US,NY,Saint Bonaventure
36,37,Graduates: English Teacher Abroad,unknown,We help teachers get safe &amp; secure jobs ab...,"Play with kids, get paid for it :-)Love travel...",University degree required. TEFL / TESOL / CEL...,See job description,0,1,0,...,unknown,Bachelor's Degree,Education Management,unknown,0,unknown,unknown,US,NY,Yonkers
37,38,PROJECT MANAGER,unknown,unknown,we are looking for a Project Manager. The Proj...,Not specified,Not mentioned,0,0,0,...,Mid-Senior level,Bachelor's Degree,Oil & Energy,Engineering,0,unknown,unknown,US,TX,HOUSTON
38,39,Art Director,Design,"We're an emerging technology agency, and we bu...",You love clients and getting to be a conduit f...,We want you if you have:3+ years of interactiv...,Why work for Mutual Mobile? We craft beautiful...,0,1,1,...,Mid-Senior level,unknown,Computer Software,Design,0,unknown,unknown,IN,AP,Hyderabad
39,40,Receptionist/Customer Service Technical Specia...,unknown,"Novitex Enterprise Solutions, formerly Pitney ...","The Receptionist will be based in Chicago, IL....",Required Qualifications:High School diploma or...,Not mentioned,0,1,0,...,Entry level,High School or equivalent,Financial Services,Administrative,0,unknown,unknown,US,IL,Chicago
40,41,English Teacher Abroad,unknown,We help teachers get safe &amp; secure jobs ab...,"Play with kids, get paid for it Love travel? J...",University degree required. TEFL / TESOL / CEL...,See job description,0,1,1,...,unknown,Bachelor's Degree,Education Management,unknown,0,unknown,unknown,US,PA,Kutztown
41,42,English Teacher Abroad,unknown,We help teachers get safe &amp; secure jobs ab...,"Play with kids, get paid for it Love travel? J...",University degree required. TEFL / TESOL / CEL...,See job description,0,1,1,...,unknown,Bachelor's Degree,Education Management,unknown,0,unknown,unknown,US,CA,Sacramento
42,43,Jr. Developer,unknown,unknown,Entry level Software DeveloperLocation : Atlan...,Not specified,Not mentioned,0,0,0,...,Entry level,Bachelor's Degree,Computer Software,Engineering,0,40000.0,50000.0,US,Unknown,Unknown
43,44,Customer Service Associate Receptionist,unknown,"Novitex Enterprise Solutions, formerly Pitney ...",The Customer Service Associate will be based i...,Minimum Requirements:Minimum of 6 months custo...,Not mentioned,0,1,0,...,Entry level,High School or equivalent,Consumer Services,Customer Service,0,unknown,unknown,US,MD,Columbia
44,45,Customer Service Team Lead,unknown,"Novitex Enterprise Solutions, formerly Pitney ...",We are currently seeking a Customer Service Te...,Required Qualifications:High school diploma or...,Not mentioned,0,1,0,...,Entry level,High School or equivalent,Computer Software,Customer Service,0,unknown,unknown,US,OK,Tulsa
45,46,Inside Sales Professional-Omaha,unknown,"ABC Supply Co., Inc. is the nation’s largest w...","As a Sales Representative, you will provide as...","As a Sales Representative, you must have the a...",Your benefits package as a Sales Representativ...,0,1,0,...,unknown,unknown,Building Materials,Sales,0,unknown,unknown,US,NE,Omaha
46,47,Entry Level,unknown,History &amp; Background The Bank started its ...,We offer diversified opportunities in various ...,-0-1 years experience English Bachelor in comm...,Not mentioned,0,0,0,...,Entry level,Bachelor's Degree,Banking,unknown,0,unknown,unknown,EG,C,
47,48,Customer Service Associate,unknown,"Novitex Enterprise Solutions, formerly Pitney ...",The Customer Service Associate will be based i...,Minimum Requirements:High school diploma or eq...,Not mentioned,0,1,0,...,Entry level,High School or equivalent,Financial Services,Administrative,0,unknown,unknown,US,TN,Brentwood
48,49,English Teacher Abroad,unknown,We help teachers get safe &amp; secure jobs ab...,"Play with kids, get paid for it Love travel? J...",University degree required. TEFL / TESOL / CEL...,See job description,0,1,1,...,unknown,Bachelor's Degree,Education Management,unknown,0,unknown,unknown,US,OH,Kent
49,50,Customer Service Team Lead,unknown,"Novitex Enterprise Solutions, formerly Pitney ...",We are currently seeking a Customer Service Te...,Required Qualifications:High school diploma or...,Not mentioned,0,1,0,...,Entry level,High School or equivalent,Facilities Services,Customer Service,0,unknown,unknown,US,NH,Dover

In [34]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
17875    False
17876    False
17877    False
17878    False
17879    False
Length: 17880, dtype: bool

In [35]:
duplicates = df[df.duplicated()]

In [36]:
duplicates.sum()

job_id                 0
title                  0
department             0
company_profile        0
description            0
requirements           0
benefits               0
telecommuting          0
has_company_logo       0
has_questions          0
employment_type        0
required_experience    0
required_education     0
industry               0
function               0
fraudulent             0
min_salary             0
max_salary             0
country                0
state                  0
city                   0
dtype: object

In [37]:
!pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\users\mohammad asif\anaconda3\lib\site-packages (2.0.25)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\mohammad asif\anaconda3\lib\site-packages (from sqlalchemy) (4.9.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\mohammad asif\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)

In [38]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\mohammad asif\anaconda3\lib\site-packages (9.2.0)

In [39]:
pip install urllib3

Requirement already satisfied: urllib3 in c:\users\mohammad asif\anaconda3\lib\site-packages (2.0.7)
Note: you may need to restart the kernel to use updated packages.

In [40]:
!pip install pymysql

Requirement already satisfied: pymysql in c:\users\mohammad asif\anaconda3\lib\site-packages (1.1.1)

In [41]:
# from sqlalchemy import create_engine
# import urllib.parse
# #mysql connection details
# username = "root"
# password = urllib.parse.quote_plus("$Mohd_asif@118384#")
# host="localhost"
# port="3306"
# database_name = "Fake_Job_Detection"

# #create the engine
# engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database_name}")


# #test connection 
# connection = engine.connect()
# print("Connected successfully!")
# connection.close()

Connected successfully!

In [43]:
 #df.to_sql(name="Job_Description1", con=engine, if_exists="replace",index=False)

17880

In [44]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [45]:
# Check target column
df['fraudulent'].value_counts()

fraudulent
0    17014
1      866
Name: count, dtype: int64

In [47]:
# Selecting features and target
X = df.drop(columns=['fraudulent'])  # Features
y = df['fraudulent']  # Target

In [50]:
# Encoding categorical variables
categorical_cols = X.select_dtypes(include=['object']).columns
X = pd.get_dummies(X, columns=categorical_cols, drop_first=True)

In [51]:
# Splitting the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [52]:
# Logistic Regression Model
log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)
y_pred_log = log_reg.predict(X_test)
print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_log))
print("Classification Report:\n", classification_report(y_test, y_pred_log))

Logistic Regression Accuracy: 0.9580536912751678
Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.99      0.98      3395
           1       0.72      0.28      0.40       181

    accuracy                           0.96      3576
   macro avg       0.84      0.64      0.69      3576
weighted avg       0.95      0.96      0.95      3576

In [53]:
# Random Forest Model
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)
print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Classification Report:\n", classification_report(y_test, y_pred_rf))

Random Forest Accuracy: 0.9843400447427293
Classification Report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99      3395
           1       1.00      0.69      0.82       181

    accuracy                           0.98      3576
   macro avg       0.99      0.85      0.90      3576
weighted avg       0.98      0.98      0.98      3576